#!/usr/bin/env bash
set -e

## other useful commands

# print project dependencies
pip freeze

# delete pycache folders
find piplanter -type d -name __pycache__ -print0 | xargs /bin/rm -rf
find pyplanter -type d -name __pycache__ -print0 | xargs /bin/rm -rf
find tests -type d -name __pycache__ -print0 | xargs /bin/rm -rf
