#!/usr/bin/env bash
set -e

source .env

rsync -avzrptl \
    --exclude="__pycache__" \
    --exclude=".git" \
    --exclude=".venv" \
    --exclude="_old" \
    --exclude="docs" \
    --exclude="*.egg-info" \
    --exclude=".mypy_cache" \
    --exclude=".pytest_cache" \
    --exclude="*coverage*" \
    --exclude="htmlcov" \
    --exclude=".github" \
    --exclude=".vscode" \
    --exclude="data" \
    --exclude="logs/" \
    --exclude="build/" \
    --exclude="dist/" \
    --del \
    ./ \
    $SSH_AUTH:$SSH_PATH
